apiVersion: apps/v1
kind: Deployment
metadata:
  name: keel
  labels:
    app: keel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keel
  template:
    metadata:
      labels:
        app: keel
    spec:
      containers:
        - name: keel
          image: keel/keel:latest
          ports:
            - containerPort: 9300
          env:
            - name: KEEL_POLICY
              value: "force"
            - name: KEEL_LOG_LEVEL
              value: "warn"
            - name: KEEL_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9300
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
