apiVersion: v1
kind: Service
metadata:
  name: keel
  namespace: keel
  labels:
    app: keel
spec:
  selector:
    app: keel
  ports:
    - protocol: TCP
      port: 9300
      targetPort: 9300
  type: ClusterIP
