apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: secure-headers
  namespace: kube-system
spec:
  headers:
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    frameDeny: true
    referrerPolicy: "strict-origin-when-cross-origin"
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
