apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: secure-ratelimit
  namespace: traefik
spec:
  rateLimit:
    average: 50
    burst: 100
    sourceCriterion:
      ipStrategy:
        depth: 1
